### ISSUE TITLE
Change button mouseover text "Edit Layers" for the Edit tool

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#10]
On the task completion page, the button mouseover text "Edit Layers" for the Edit tool should be changed to "Move Circle" or, probably "Change Circle" as a parallel to the mouseover "Draw a Circle" for the Circle tool. This would be a modification that accomodates the particular needs of the UU projects, which will only use only the circle georeferencing tool.

**Comment by shahmanash** [comment]
Fixed 3725012ac28dfb8434afcc693a44be1f07f7ba02
