### ISSUE TITLE
Non-admin user privileges should be checked

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#17]
Only an admin should have the ability to "Create" a project, so non-admin user privileges should be checked.

**Comment by kcholston** [comment]
Access to Community pages has been restricted to registered users.

**Comment by kcholston** [comment]
A non-Admin user should not be presented with the "Create/Skapa" tab. The first set of users tried to begin contributing using that tab.

**Comment by shahmanash** [comment]
Fix 5e31c0ee306d9ca0c48abb86f36fa1c768d53f7d
