### ISSUE TITLE
Change categories used to group projects to more easily understandable terms

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#19]
The Pybossa categories used to group projects are difficult to understand. It is unclear whether they can be changed to more easily understandable, colloquial terms from:
	historical contributions
	thinking projects
	volunteer sensing
	draft

**Comment by shahmanash** [comment]
Fixed in #24 
Fixed 4e2b104
Added new categories and removed old irrelevant ones from database.
