### ISSUE TITLE
Changes to text: "About"

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#31]
"Arbetet med våra naturhistoriska samlingar har traditionellt utförts av museiintendenter, taxonomiska experter och entusiastiska volontärer. Inom projekten för BioAtlas Medborgarforskning utökar och utvecklar vi samarbetet vidare med medborgarforskning, och möjliggör därmed insamling av större mängder data. Inom BioAtlas samlas olika digitaliseringsprojekt med..." See Google Document

**Comment by shahmanash** [comment]
Fixed 09d6e337a592c2123697d3407b43fd7d9b1cd23b 6e908a409ce73a20a3dab4002bc8d21d7ce19fdd
