### ISSUE TITLE
Remove or alter section "Powered by Pybossa" with links

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#5]
The landing page (https://pybossa.bioatlas.se) includes a bordered section of text and links (begins with "Powered by Pybossa"). It functions as a secondary footer above the Bioatlas footer and may be a bureaucratic distraction from the intended user experience. If possible, remove this section.

**Comment by shahmanash** [comment]
Fixed df619b73df29d2d7463eda0c803a497faff30e61

**Comment by shahmanash** [comment]
Fixed df619b73df29d2d7463eda0c803a497faff30e61
