### ISSUE TITLE
Too many logos in the Bioatlas footer

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#6]
Because this crowdsourcing trial involves only UU, there is a perception that there are too many logos in the Bioatlas footer. An alternative footer has not been suggested, but reducing the number of logos is implied (could reflect the institutions with Bioatlas crowdsourcing projects).

**Comment by shahmanash** [comment]
Fixed df619b73df29d2d7463eda0c803a497faff30e61
