### ISSUE TITLE
Museum project subcategorization

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#7]
There will be four Pybossa projects from UU but there does not seem to be a way to identify them as a subcategorized group. A museum project subcategorization is primarily a concern for post-trial work, when other museums may have projects. Note that the groupings refer to data ownership; support of particpation can involve several institutions.

**Comment by kcholston** [comment]
The solution for handling this subcategorization is to create new project categories (see https://github.com/bioatlas/pybossa-default-theme/issues/19) that are more relevant to the project administrators. A category for Evolutionsmuseet, Uppsala, could be created if the intent is to group by collection/herbarium, institution (or institutional partners).

**Comment by shahmanash** [comment]
Fixed in #24 
Fixed 4e2b104
Added new categories and removed old irrelevant ones from database.
