### ISSUE TITLE
Swedish translations for the text and buttons

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#8]
Considering the target audience, there is a desire to have more Swedish translations for the text and buttons. Current solutions have been "double" translations in English and Swedish for fields in the task completion page (to label fields/columns exposed to the user from the dataset).

**Comment by shahmanash** [comment]
Fixed abacc361cc03db4a90d858234c198e6bbf4cfc96 806e5d9bf42f33bdc5bb3e8e5eda1b1624949a5f aca1680817ed30d38d18f78bf5ad446026487c0e
