### ISSUE TITLE
User options for the circle tool are difficult to interpret

### ISSUE THREAD

**Issue by kcholston** [bioatlas/pybossa-default-theme#9]
On the task completion page, <Save><Cancel><Clear All> user options for the circle tool are difficult to interpret. "Clear All" should be changed to "Clear". "Save" seemed to have no purpose, operates like "Clear" because the circle "... goes away...." This second observation shows that the user did not notice that the coordinates and uncertainty were saved to the appropriate fields, only that the circle disappeared. This may be explained in the Help pages.

**Comment by shahmanash** [comment]
Fixed 3725012ac28dfb8434afcc693a44be1f07f7ba02
